### ISSUE TITLE
请问下. 这个组件是否能支持 ssr?

### ISSUE THREAD

**Issue by didilinkin** [Cacivy/react-textscroll#2]
我在 next.js 项目中引入 此项目， 会报错.

所以想确认下 在其他ssr 项目中 是否能使用? 看了下报错信息. 貌似是 styled 未配置 服务端的功能

我也在使用 styled 在服务端中使用它，配置有点麻烦.

有什么好的建议吗？

目前的替代方案是 ： **animate.css** 有点丑陋

**Comment by Cacivy** [comment]
很抱歉，因为组件中使用了componentWillMount生命周期，所以在ssr中会带来一些问题，可以Fork后进行修改
[](另外关于styled在next.js使用可以参考[nextjs--styled-components-the-really-simple-guide](https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c))

**Comment by Cacivy** [comment]
另外关于在next.js使用styled，可以参考[nextjs--styled-components-the-really-simple-guide](https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c)
